const GET_COURSES_BEGIN = 'GET_COURSE_BEGIN'
const GET_COURSES_SUCCESS = 'GET_COURSES_SUCCESS'
const GET_COURSES_ERROR = 'GET_COURSES_ERROR'
const ADD_COURSE_BEGIN = 'ADD_COURSE_BEGIN'
const ADD_COURSE_SUCCESS = 'ADD_COURSE_SUCCESS'
const ADD_COURSE_ERROR = 'ADD_COURSE_ERROR'
const OPEN_ADD_COURSE_MODAL = 'OPEN_ADD_COURSE_MODAL'
const CLOSE_ADD_COURSE_MODAL = 'CLOSE_ADD_COURSE_MODAL'
const ADD_LESSON_BEGIN = 'ADD_LESSON_BEGIN'
const DELETE_LESSON_BEGIN = 'DELETE_LESSON_BEGIN'
const SAVE_LESSON_BEGIN = 'SAVE_LESSON_BEGIN'
const ADD_LESSON_SUCCESS = 'ADD_LESSON_SUCCESS'
const DELETE_LESSON_SUCCESS = 'DELETE_LESSON_SUCCESS'
const SAVE_LESSON_SUCCESS = 'SAVE_LESSON_SUCCESS'
const ADD_LESSON_ERROR = 'ADD_LESSON_ERROR'
const DELETE_LESSON_ERROR = 'DELETE_LESSON_ERROR'
const SAVE_LESSON_ERROR = 'SAVE_LESSON_ERROR'
const ERROR = 'ERROR'
const REMOVE_ERROR = 'REMOVE_ERROR'
const GET_LESSONS_BEGIN = 'GET_LESSONS_BEGIN'
const GET_LESSONS_SUCCESS = 'GET_LESSONS_SUCCESS'
const GET_LESSONS_ERROR = 'GET_LESSONS_ERROR'
const FORBIDDEN_WORDS = ['spam', 'money']

export {
    GET_COURSES_BEGIN,
    GET_COURSES_SUCCESS,
    GET_COURSES_ERROR,
    ADD_COURSE_BEGIN,
    ADD_COURSE_SUCCESS,
    ADD_COURSE_ERROR,
    OPEN_ADD_COURSE_MODAL,
    CLOSE_ADD_COURSE_MODAL,
    ADD_LESSON_BEGIN,
    DELETE_LESSON_BEGIN,
    SAVE_LESSON_BEGIN,
    ADD_LESSON_SUCCESS,
    DELETE_LESSON_SUCCESS,
    SAVE_LESSON_SUCCESS,
    ADD_LESSON_ERROR,
    DELETE_LESSON_ERROR,
    SAVE_LESSON_ERROR,
    GET_LESSONS_BEGIN,
    GET_LESSONS_SUCCESS,
    GET_LESSONS_ERROR,
    ERROR,
    REMOVE_ERROR,
    FORBIDDEN_WORDS
}