const ADD_TODO = 'ADD_TODO'
const REMOVE_TODO = 'REMOVE_TODO'
const EDIT_TODO = 'EDIT_TODO'
const ENABLE_TODO = 'REMOVE_DISABLED'
const COMPLETE_TODO = 'COMPLETE_TODO'
const ERROR = 'ERROR'
const REMOVE_ERROR = 'REMOVE_ERROR'
const FORBIDDEN_WORDS = ['spam', 'money']
const INCREMENT = 'INCREMENT'
const DECREMENT = 'DECREMENT'

export {ADD_TODO, REMOVE_TODO, ENABLE_TODO, EDIT_TODO, INCREMENT, DECREMENT, FORBIDDEN_WORDS, ERROR, REMOVE_ERROR}