const GET_COURSES_BEGIN = 'GET_COURSE_BEGIN'
const GET_COURSES_SUCCESS = 'GET_COURSES_SUCCESS'
const GET_COURSES_ERROR = 'GET_COURSES_ERROR'
const ADD_COURSE_BEGIN = 'ADD_COURSE_BEGIN'
const ADD_COURSE_SUCCESS = 'ADD_COURSE_SUCCESS'
const ADD_COURSE_ERROR = 'ADD_COURSE_ERROR'
const OPEN_ADD_COURSE_MODAL = 'OPEN_ADD_COURSE_MODAL'
const CLOSE_ADD_COURSE_MODAL = 'CLOSE_ADD_COURSE_MODAL'
const ADD_TODO = 'ADD_TODO'
const REMOVE_TODO = 'REMOVE_TODO'
const EDIT_TODO = 'EDIT_TODO'
const SELECT_TODO = 'SELECT_TODO'
const ENABLE_TODO = 'ENABLE_TODO'
const ERROR = 'ERROR'
const REMOVE_ERROR = 'REMOVE_ERROR'
const FORBIDDEN_WORDS = ['spam', 'money']
const INCREMENT = 'INCREMENT'
const DECREMENT = 'DECREMENT'

export {
    GET_COURSES_BEGIN,
    GET_COURSES_SUCCESS,
    GET_COURSES_ERROR,
    ADD_COURSE_BEGIN,
    ADD_COURSE_SUCCESS,
    ADD_COURSE_ERROR,
    OPEN_ADD_COURSE_MODAL,
    CLOSE_ADD_COURSE_MODAL,
    ADD_TODO,
    REMOVE_TODO,
    ENABLE_TODO,
    EDIT_TODO,
    SELECT_TODO,
    INCREMENT,
    DECREMENT,
    FORBIDDEN_WORDS,
    ERROR,
    REMOVE_ERROR
}